# Site settings
title: Frojas github pages
email: frojas@alumnos.utalca.cl
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/github-pages-sandbox" # the subpath of your site, e.g. /blog/
url: "https://frojasg.github.io" # the base hostname & protocol for your site
twitter_username: frojasg
github_username:  frojasg

# Build settings
markdown: kramdown
